title: Jeremiah (Jay) Geneve # your name (or website title) here
logo: "/images/Jeremiah Geneve.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <a href="https://www.linkedin.com/in/jeremiah-geneve/">LinkedIn</a> 
  <br>
  <a href="/pdf/Jeremiah%20Geneve%20Resume%20(Technology)?raw=true" class="btn btn--info">Resume</a>
  <br>
  <a href="https://github.com/JayGeneve">GitHub</a>  
  
theme: jekyll-theme-minimal
